job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, and it's cool!")
    scm {
        git("https://github.com/RahulNaik-Java/SpringBootDocker.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    tools {
        maven "local"
        jdk "local_java_19"
    }
    steps {
        maven('clean package', 'SpringBootDocker/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}