pipeline {
    agent any
    tools {
            maven "local"
            jdk "local_java_19"
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f SpringBootDocker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_Appln_To_Stage_Env'

            }

        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Appln_To_Prod_Env'
            }
        }
    }
}

// Sample Code below

/* pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, Rahul here, from India'
                        echo 'We are Starting the Testing'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying in Staging Area"
                  }
            }
            stage('Deploy Production') {
                  steps {
                        echo "Deploying in Production Area"
                  }
            }
            stage('Finished Deployment in Prod') {
                              steps {
                                    echo "Finished deployment in Production Area"
                              }
                        }
      }
} */

