pipeline {
    agent any
    tools {
        maven "3.9.3"
        jdk "open-jdk-19.0.2"
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f SpringBootDocker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}


// Sample Code below

/* pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, Rahul here, from India'
                        echo 'We are Starting the Testing'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying in Staging Area"
                  }
            }
            stage('Deploy Production') {
                  steps {
                        echo "Deploying in Production Area"
                  }
            }
            stage('Finished Deployment in Prod') {
                              steps {
                                    echo "Finished deployment in Production Area"
                              }
                        }
      }
} */

